sudo: required

services:
    -docker

before_install:
    - docker build -f ./client/Dockerfile.dev -t kpkeerthi25/docker-react-test .
scripts:
    - docker run -e CI=true kpkeerthi25/docker-react npm run test

after_success:
    - docker build -t kpkeerthi25/multi-client ./client
    - docker build -t kpkeerthi25/multi-nginx ./nginx
    - docker build -t kpkeerthi25/multi-server ./server
    - echo "$Docker_pass" | docker login -u "$Docker_id" --password-stdin
    - docker push kpkeerthi25/multi-client
    - docker push kpkeerthi25/multi-nginx 
    - docker push kpkeerthi25/multi-server
