sudo: required

services:
    -docker

addons:
    ssh_known_hosts: 206.189.136.60

before_install:
    - docker build -t kpkeerthi25/docker-react-test -f ./client/Dockerfile.dev ./client
scripts:
    - docker run -e CI=true kpkeerthi25/docker-react-test npm run test

after_success:
    - docker build -t kpkeerthi25/multi-client ./client
    - docker build -t kpkeerthi25/multi-nginx ./nginx
    - docker build -t kpkeerthi25/multi-server ./server
    - echo "$Docker_pass" | docker login -u "$Docker_id" --password-stdin
    - docker push kpkeerthi25/multi-client:latest
    - docker push kpkeerthi25/multi-nginx:latest
    - docker push kpkeerthi25/multi-server:latest
    - ssh keerthi@206.189.136.60
    - docker-compose down
    - docker-compose up -d
