version: '3'

services: 
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        tty: true
    
    api:
        build: 
            context: ./server
            dockerfile: Dockerfile

    nginx:
        restart: always
        build: 
            context: ./nginx
        ports: 
            - 45678:80
